### ISSUE TITLE
consumet/api no longer works. 

### ISSUE THREAD

**Issue by M-YasirGhaffar** [Khanhtran47/Sora#381]
The project seems to be working fine after a few small adjustments to the node versions but video player is not working at all. The consumet API returns with an error:

```
GET /movies/519182/watch?provider=Flixhq&id=movie%2Fwatch-despicable-me-19486&_data=root 200 - - 285.819 ms
Updated the cache value for tmdb-movie-detail-519182-undefined. Getting a fresh value for this took 686ms. Caching for 86400000ms + 604800000ms stale in LRU.
Error: Request failed with status code 404
    at FlixHQ.fetchEpisodeSources (C:\Users\<RemovedUsername>\Desktop\Sora\node_modules\.pnpm\@consumet+extensions@https+++codeload.github.com+consumet+consumet.ts+tar.gz+d71bdcad5ab1f9f82e9e92b1ca8447e899059b34\node_modules\@consumet\extensions\src\providers\movies\flixhq.ts:227:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.getFreshValue (C:\Users\<UserName>\Desktop\Sora\app\services\tmdb\tmdb.server.ts:693:21)
Updated the cache value for tmdb-movie/watch-despicable-me-19486-episode-19486-watch. Getting a fresh value for this took 1346ms. Caching for 3600000ms + 10800000ms stale in LRU.
```

Are the developers looking into fixing this anytime?

**Comment by RounakDadsena** [comment]
dm me on discord

**Comment by M-YasirGhaffar** [comment]
Can you provide your discord?

**Comment by RounakDadsena** [comment]
roemail: [filmu08@gmail.com](mailto:filmu08@gmail.com)
discord: RounakDadsena#2641

**Comment by M-YasirGhaffar** [comment]
@RounakDadsena Did receive any response. Mailed you few days back.

**Comment by RounakDadsena** [comment]
okay wait

**Comment by DeaxTV** [comment]
@RounakDadsena I mailed you as well if you can help me i would really appreciate it.
